# Generated by Django 2.0.7 on 2018-09-23 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HpcCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=250, unique=True)),
                ('key', models.TextField(blank=True)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(blank=True, max_length=1024)),
                ('client_path', models.CharField(default='', max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='HpcJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpus', models.IntegerField(default=1)),
                ('ram', models.IntegerField(default=100)),
                ('job_status', models.IntegerField(default=None, null=True)),
                ('job_submitted_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_queued_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('job_finished_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('cluster', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_hpc_job_controller.HpcCluster')),
            ],
        ),
        migrations.CreateModel(
            name='WebsocketToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('used', models.BooleanField(default=False)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_hpc_job_controller.HpcCluster')),
            ],
        ),
    ]
