# Generated by Django 2.0.7 on 2018-09-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hpc_job_controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websockettoken',
            name='is_file',
            field=models.BooleanField(default=False),
        ),
    ]
