# Generated by Django 2.0.7 on 2018-09-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hpc_job_controller', '0003_auto_20180926_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpcjob',
            name='job_details',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hpcjob',
            name='job_parameters',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hpcjob',
            name='remote_job_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
