# Generated by Django 2.0.7 on 2018-09-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hpc_job_controller', '0004_auto_20180926_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpcjob',
            name='job_submitting_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
