# Generated by Django 2.0.7 on 2018-10-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hpc_job_controller', '0005_hpcjob_job_submitting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hpcjob',
            name='remote_job_id',
        ),
        migrations.AddField(
            model_name='hpcjob',
            name='job_running_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
