# Generated by Django 2.0.7 on 2018-10-25 01:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_hpc_job_controller', '0006_auto_20181005_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='websockettoken',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
