# Generated by Django 2.1.5 on 2019-06-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hpc_job_controller', '0007_websockettoken_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpccluster',
            name='host_name',
            field=models.CharField(max_length=250),
        ),
    ]
