# Generated by Django 2.2.3 on 2019-07-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hpc_job_controller', '0008_auto_20190604_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpccluster',
            name='client_path',
            field=models.CharField(default='', help_text='Host name and Client path must be unique together.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='hpccluster',
            name='host_name',
            field=models.CharField(help_text='Host name and Client path must be unique together.', max_length=250),
        ),
    ]
