# Generated by Django 2.2.3 on 2019-08-07 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_hpc_job_controller', '0009_auto_20190722_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpcjob',
            name='cluster',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_hpc_job_controller.HpcCluster'),
        ),
        migrations.AlterField(
            model_name='hpcjob',
            name='job_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
